version: 19.12

#
# Configuration for an IAG container.
#
# This file specifies access control and rate limiting policies.  It is
# designed to be used with a configuration file specifying basic configuration.
#

policies:

  authorization:
    - name: "readinfo_access"
      methods:
        - "GET"
      paths:
        - "/demo/page/admin/readinfo"
      rule: "anyuser"
      action: "permit"

    - name: "admin_access"
      paths:
        - "/demo/page/admin"
        - "/demo/page/admin/*"
      rule: not (any groupIds = "admin")
      action: "deny"

    - name: "public"
      paths:
        - "/"
        - "/favicon.ico"
        - "/demo"
        - "/demo/stylesheets/*"
        - "/demo/userlogin"
        - "/demo/userlogin/pwdcheck"
      rule: "anyuser"
      action: "permit"

  rate_limiting:
    - name: "limited_by_ip"
      paths:
        - "/demo/page/limited"
        - "/demo/page/limited/*"
      methods:
        - "*"
      rule: |
        credential: 'AZN_CRED_PRINCIPAL_NAME = "*"'
        ip: false
        capacity: 3
        interval: 10
        reaction: TEMPLATE

    - name: "hard_limit_by_ip"
      paths:
        - "/demo/page/limited/hard"
      methods:
        - "*"
      rule: |
        ip: true
        capacity: 5
        interval: 10
        reaction: CLOSE
